# Generated by Django 5.1.5 on 2025-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mandelbrot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandelbrotview",
            name="name",
            field=models.CharField(default="Test View", max_length=128),
            preserve_default=False,
        ),
    ]
