# Generated by Django 5.1.5 on 2025-03-05 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mandelbrot", "0002_mandelbrotview_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandelbrotview",
            name="view_type",
            field=models.CharField(
                choices=[
                    ("user_defined", "User Defined"),
                    ("predefined", "Predefined"),
                ],
                default="user_defined",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mandelbrotview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_mandelbrot_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
